//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("DateCalculatorDBModel", "FK_tblHoliday_tblCountry", "tblCountry", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DateCalculatorVS2008.DAL.tblCountry), "tblHoliday", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DateCalculatorVS2008.DAL.tblHoliday))]

// Original file name:
// Generation date: 9/5/2013 12:22:11 PM
namespace DateCalculatorVS2008.DAL
{
    
    /// <summary>
    /// There are no comments for DateCalculatorDBEntities in the schema.
    /// </summary>
    public partial class DateCalculatorDBEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new DateCalculatorDBEntities object using the connection string found in the 'DateCalculatorDBEntities' section of the application configuration file.
        /// </summary>
        public DateCalculatorDBEntities() : 
                base("name=DateCalculatorDBEntities", "DateCalculatorDBEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new DateCalculatorDBEntities object.
        /// </summary>
        public DateCalculatorDBEntities(string connectionString) : 
                base(connectionString, "DateCalculatorDBEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new DateCalculatorDBEntities object.
        /// </summary>
        public DateCalculatorDBEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "DateCalculatorDBEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for tblCountries in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<tblCountry> tblCountries
        {
            get
            {
                if ((this._tblCountries == null))
                {
                    this._tblCountries = base.CreateQuery<tblCountry>("[tblCountries]");
                }
                return this._tblCountries;
            }
        }
        private global::System.Data.Objects.ObjectQuery<tblCountry> _tblCountries;
        /// <summary>
        /// There are no comments for tblHolidays in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<tblHoliday> tblHolidays
        {
            get
            {
                if ((this._tblHolidays == null))
                {
                    this._tblHolidays = base.CreateQuery<tblHoliday>("[tblHolidays]");
                }
                return this._tblHolidays;
            }
        }
        private global::System.Data.Objects.ObjectQuery<tblHoliday> _tblHolidays;
        /// <summary>
        /// There are no comments for tblCountries in the schema.
        /// </summary>
        public void AddTotblCountries(tblCountry tblCountry)
        {
            base.AddObject("tblCountries", tblCountry);
        }
        /// <summary>
        /// There are no comments for tblHolidays in the schema.
        /// </summary>
        public void AddTotblHolidays(tblHoliday tblHoliday)
        {
            base.AddObject("tblHolidays", tblHoliday);
        }
    }
    /// <summary>
    /// There are no comments for DateCalculatorDBModel.tblCountry in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="DateCalculatorDBModel", Name="tblCountry")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class tblCountry : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new tblCountry object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="code">Initial value of Code.</param>
        public static tblCountry CreatetblCountry(int id, string name, string code)
        {
            tblCountry tblCountry = new tblCountry();
            tblCountry.ID = id;
            tblCountry.Name = name;
            tblCountry.Code = code;
            return tblCountry;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Code in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this._Code;
            }
            set
            {
                this.OnCodeChanging(value);
                this.ReportPropertyChanging("Code");
                this._Code = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Code");
                this.OnCodeChanged();
            }
        }
        private string _Code;
        partial void OnCodeChanging(string value);
        partial void OnCodeChanged();
        /// <summary>
        /// There are no comments for tblHolidays in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("DateCalculatorDBModel", "FK_tblHoliday_tblCountry", "tblHoliday")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<tblHoliday> tblHolidays
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<tblHoliday>("DateCalculatorDBModel.FK_tblHoliday_tblCountry", "tblHoliday");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<tblHoliday>("DateCalculatorDBModel.FK_tblHoliday_tblCountry", "tblHoliday", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for DateCalculatorDBModel.tblHoliday in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="DateCalculatorDBModel", Name="tblHoliday")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class tblHoliday : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new tblHoliday object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="date">Initial value of Date.</param>
        public static tblHoliday CreatetblHoliday(int id, global::System.DateTime date)
        {
            tblHoliday tblHoliday = new tblHoliday();
            tblHoliday.ID = id;
            tblHoliday.Date = date;
            return tblHoliday;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property HolidayName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string HolidayName
        {
            get
            {
                return this._HolidayName;
            }
            set
            {
                this.OnHolidayNameChanging(value);
                this.ReportPropertyChanging("HolidayName");
                this._HolidayName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("HolidayName");
                this.OnHolidayNameChanged();
            }
        }
        private string _HolidayName;
        partial void OnHolidayNameChanging(string value);
        partial void OnHolidayNameChanged();
        /// <summary>
        /// There are no comments for Property Date in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this.ReportPropertyChanging("Date");
                this._Date = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Date");
                this.OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
        /// <summary>
        /// There are no comments for Property DayObserved in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string DayObserved
        {
            get
            {
                return this._DayObserved;
            }
            set
            {
                this.OnDayObservedChanging(value);
                this.ReportPropertyChanging("DayObserved");
                this._DayObserved = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("DayObserved");
                this.OnDayObservedChanged();
            }
        }
        private string _DayObserved;
        partial void OnDayObservedChanging(string value);
        partial void OnDayObservedChanged();
        /// <summary>
        /// There are no comments for tblCountry in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("DateCalculatorDBModel", "FK_tblHoliday_tblCountry", "tblCountry")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public tblCountry tblCountry
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<tblCountry>("DateCalculatorDBModel.FK_tblHoliday_tblCountry", "tblCountry").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<tblCountry>("DateCalculatorDBModel.FK_tblHoliday_tblCountry", "tblCountry").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for tblCountry in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<tblCountry> tblCountryReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<tblCountry>("DateCalculatorDBModel.FK_tblHoliday_tblCountry", "tblCountry");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<tblCountry>("DateCalculatorDBModel.FK_tblHoliday_tblCountry", "tblCountry", value);
                }
            }
        }
    }
}
